database: postgres:///bostonruby
page_title: relevancers
poll_interval: 10
org: 
  name: relevance.com
  href: http://thinkrelevance.com
opml: http://relevancers.herokuapp.com/relevance-blogs.xml
twitters: https://github.com/bostonrb/bostonrb/wiki/All-Rubyists
language: ruby
locations: 
- cambridge+ma 
- boston 
- somerville+ma 
- salem+ma 
- providence+ri 
- salem+ma 
- portsmouth+nh 
- portland+me
hackers:
- alandipert
- bobby
- cldwalker
- itsthatguy
- karnowski
- lynngrogan
- michaelparenteau
- mtnygard
- redinger
- rkneufeld
- rsanheim
- spicycode
- aredington
- brentonashworth
- bvandgrift
- candera
- crnixon
- ErgoBibamus
- fogus
- jasonrudolph
- jdpace
- jenmyers
- jgehtland
- jgkite
- jondistad
- ldenman
- levand
- liebke
- MaggieL
- muness
- NaokoChamberlain
- relevance
- russolsen
- stuarthalloway
- stuartsierra
- sumbach
- timewald
- turbomarc
- relevantandrew
tweeters:
- antiheroine
- L4k3
- gabrielcoch
- spicycode
- rkneufeld
- cldwalker
- itg
- brentonashworth
- russolsen
- crnixon
- mtnygard
- bvandgrift
- MaggieLitton
- fogus
- jgkite
- turbomarc
- samumbach
- levanderhart
- bobbycalderwood
- craigandera
- JAlexWarr
- holy_chao
- stuartsierra
- jondistad
- alandipert
- liebke
- parenteau
- jdpace
- redinger
- muness
- abedra
- rsanheim
- karnowski
- jgehtland
- stuarthalloway
- jessmartin
- thinkrelevance
- jasonrudolph
